const prismLanguages = {
    markup: ["Markup", ["markup","html","xml","svg","mathml","ssml","atom","rss"]],
    css: ["CSS", ["css"]],
    clike: ["C‑like", ["clike"]],
    javascript: ["JavaScript", ["javascript","js"]],
    abap: ["ABAP", ["abap"]],
    abnf: ["Augmented Backus–Naur form", ["abnf"]],
    actionscript: ["ActionScript", ["actionscript"]],
    ada: ["Ada", ["ada"]],
    antlr4: ["ANTLR4", ["antlr4","g4"]],
    apacheconf: ["Apache Configuration", ["apacheconf"]],
    apl: ["APL", ["apl"]],
    applescript: ["AppleScript", ["applescript"]],
    aql: ["AQL", ["aql"]],
    arduino: ["Arduino", ["arduino"]],
    arff: ["ARFF", ["arff"]],
    asciidoc: ["AsciiDoc", ["asciidoc","adoc"]],
    asm6502: ["6502 Assembly", ["asm6502"]],
    aspnet: ["ASP.NET (C#)", ["aspnet"]],
    autohotkey: ["AutoHotkey", ["autohotkey"]],
    autoit: ["AutoIt", ["autoit"]],
    bash: ["Bash", ["bash","shell"]],
    basic: ["BASIC", ["basic"]],
    batch: ["Batch", ["batch"]],
    bbcode: ["BBcode", ["bbcode"]],
    bison: ["Bison", ["bison"]],
    bnf: ["Backus–Naur form", ["bnf","rbnf"]],
    brightscript: ["BrightScript", ["brightscript"]],
    bro: ["Bro", ["bro"]],
    c: ["C", ["c"]],
    csharp: ["C#", ["csharp","cs","dotnet"]],
    cpp: ["C++", ["cpp"]],
    cil: ["CIL", ["cil"]],
    coffeescript: ["CoffeeScript", ["coffeescript","coffee"]],
    cmake: ["CMake", ["cmake"]],
    clojure: ["Clojure", ["clojure"]],
    crystal: ["Crystal", ["crystal"]],
    csp: ["Content-Security-Policy", ["csp"]],
    "css-extras": ["CSS Extras", ["css-extras"]],
    d: ["D", ["d"]],
    dart: ["Dart", ["dart"]],
    diff: ["Diff", ["diff"]],
    django: ["Django/Jinja2", ["django","jinja2"]],
    "dns-zone-file": ["DNS zone file", ["dns-zone-file","dns-zone"]],
    docker: ["Docker", ["docker","dockerfile"]],
    ebnf: ["Extended Backus–Naur form", ["ebnf"]],
    eiffel: ["Eiffel", ["eiffel"]],
    ejs: ["EJS", ["ejs"]],
    elixir: ["Elixir", ["elixir"]],
    elm: ["Elm", ["elm"]],
    etlua: ["Embedded Lua templating", ["etlua"]],
    erb: ["ERB", ["erb"]],
    erlang: ["Erlang", ["erlang"]],
    fsharp: ["F#", ["fsharp"]],
    "firestore-security-rules": ["Firestore security rules", ["firestore-security-rules"]],
    flow: ["Flow", ["flow"]],
    fortran: ["Fortran", ["fortran"]],
    ftl: ["FreeMarker Template Language", ["ftl"]],
    "gcode": ["G‑code", ["gcode"]],
    gdscript: ["GDScript", ["gdscript"]],
    gedcom: ["GEDCOM", ["gedcom"]],
    gherkin: ["Gherkin", ["gherkin"]],
    git: ["Git", ["git"]],
    glsl: ["GLSL", ["glsl"]],
    gml: ["GameMaker Language", ["gml","gamemakerlanguage"]],
    go: ["Go", ["go"]],
    graphql: ["GraphQL", ["graphql"]],
    groovy: ["Groovy", ["groovy"]],
    haml: ["Haml", ["haml"]],
    handlebars: ["Handlebars", ["handlebars"]],
    haskell: ["Haskell", ["haskell","hs"]],
    haxe: ["Haxe", ["haxe"]],
    hcl: ["HCL", ["hcl"]],
    http: ["HTTP", ["http"]],
    hpkp: ["HTTP Public-Key-Pins", ["hpkp"]],
    hsts: ["HTTP Strict‑Transport‑Security", ["hsts"]],
    ichigojam: ["IchigoJam", ["ichigojam"]],
    icon: ["Icon", ["icon"]],
    inform7: ["Inform 7", ["inform7"]],
    ini: ["Ini", ["ini"]],
    io: ["Io", ["io"]],
    j: ["J", ["j"]],
    java: ["Java", ["java"]],
    javadoc: ["JavaDoc", ["javadoc"]],
    javadoclike: ["JavaDoc‑like", ["javadoclike"]],
    javastacktrace: ["Java stack trace", ["javastacktrace"]],
    jolie: ["Jolie", ["jolie"]],
    jq: ["JQ", ["jq"]],
    jsdoc: ["JSDoc", ["jsdoc"]],
    "js-extras": ["JS Extras", ["js-extras"]],
    "js-templates": ["JS Templates", ["js-templates"]],
    json: ["JSON", ["json"]],
    jsonp: ["JSONP", ["jsonp"]],
    json5: ["JSON5", ["json5"]],
    julia: ["Julia", ["julia"]],
    keyman: ["Keyman", ["keyman"]],
    kotlin: ["Kotlin", ["kotlin"]],
    latex: ["LaTeX", ["latex","tex","context"]],
    less: ["Less", ["less"]],
    lilypond: ["LilyPond", ["lilypond","ly"]],
    liquid: ["Liquid", ["liquid"]],
    lisp: ["Lisp", ["lisp","emacs","elisp","emacs-lisp"]],
    livescript: ["LiveScript", ["livescript"]],
    lolcode: ["LOLCODE", ["lolcode"]],
    lua: ["Lua", ["lua"]],
    makefile: ["Makefile", ["makefile"]],
    markdown: ["Markdown", ["markdown","md"]],
    "markup-templating": ["Markup templating", ["markup-templating"]],
    matlab: ["MATLAB", ["matlab"]],
    mel: ["MEL", ["mel"]],
    mizar: ["Mizar", ["mizar"]],
    monkey: ["Monkey", ["monkey"]],
    moonscript: ["MoonScript", ["moonscript","moon"]],
    n1ql: ["N1QL", ["n1ql"]],
    n4js: ["N4JS", ["n4js","n4jsd"]],
    "nand2tetris-hdl": ["Nand To Tetris HDL", ["nand2tetris-hdl"]],
    nasm: ["NASM", ["nasm"]],
    nginx: ["nginx", ["nginx"]],
    nim: ["Nim", ["nim"]],
    nix: ["Nix", ["nix"]],
    nsis: ["NSIS", ["nsis"]],
    objectivec: ["Objective‑C", ["objectivec"]],
    ocaml: ["OCaml", ["ocaml"]],
    opencl: ["OpenCL", ["opencl"]],
    oz: ["Oz", ["oz"]],
    parigp: ["PARI/GP", ["parigp"]],
    parser: ["Parser", ["parser"]],
    pascal: ["Pascal", ["pascal","objectpascal"]],
    perl: ["Perl", ["perl"]],
    php: ["PHP", ["php"]],
    phpdoc: ["PHPDoc", ["phpdoc"]],
    "php-extras": ["PHP Extras", ["php-extras"]],
    plsql: ["PL/SQL", ["plsql"]],
    powershell: ["PowerShell", ["powershell"]],
    processing: ["Processing", ["processing"]],
    prolog: ["Prolog", ["prolog"]],
    properties: [".properties", ["properties"]],
    protobuf: ["Protocol Buffers", ["protobuf"]],
    pug: ["Pug", ["pug"]],
    puppet: ["Puppet", ["puppet"]],
    pure: ["Pure", ["pure"]],
    python: ["Python", ["python","py"]],
    q: ["Q (kdb+ database)", ["q"]],
    qore: ["Qore", ["qore"]],
    r: ["R", ["r"]],
    jsx: ["React JSX", ["jsx"]],
    tsx: ["React TSX", ["tsx"]],
    renpy: ["Ren’py", ["renpy"]],
    reason: ["Reason", ["reason"]],
    regex: ["Regex", ["regex"]],
    rest: ["reST (reStructuredText)", ["rest"]],
    rip: ["Rip", ["rip"]],
    roboconf: ["Roboconf", ["roboconf"]],
    ruby: ["Ruby", ["ruby","rb"]],
    rust: ["Rust", ["rust"]],
    sas: ["SAS", ["sas"]],
    sass: ["Sass (Sass)", ["sass"]],
    scss: ["Sass (Scss)", ["scss"]],
    scala: ["Scala", ["scala"]],
    scheme: ["Scheme", ["scheme"]],
    "shell-session": ["Shell session", ["shell-session"]],
    smalltalk: ["Smalltalk", ["smalltalk"]],
    smarty: ["Smarty", ["smarty"]],
    solidity: ["Solidity (Ethereum)", ["solidity"]],
    soy: ["Soy (Closure Template)", ["soy"]],
    sparql: ["SPARQL", ["sparql","rq"]],
    "splunk-spl": ["Splunk SPL", ["splunk-spl"]],
    sqf: ["SQF (Arma 3)", ["sqf"]],
    sql: ["SQL", ["sql"]],
    stylus: ["Stylus", ["stylus"]],
    swift: ["Swift", ["swift"]],
    tap: ["TAP", ["tap"]],
    tcl: ["Tcl", ["tcl"]],
    textile: ["Textile", ["textile"]],
    toml: ["TOML", ["toml"]],
    tt2: ["Template Toolkit 2", ["tt2"]],
    turtle: ["Turtle", ["turtle","trig"]],
    twig: ["Twig", ["twig"]],
    typescript: ["TypeScript", ["typescript","ts"]],
    "t4-cs": ["T4 Text Templates (C#)", ["t4-cs","t4"]],
    "t4-vb": ["T4 Text Templates (VB)", ["t4-vb"]],
    "t4-templating": ["T4 templating", ["t4-templating"]],
    vala: ["Vala", ["vala"]],
    vbnet: ["VB.Net", ["vbnet"]],
    velocity: ["Velocity", ["velocity"]],
    verilog: ["Verilog", ["verilog"]],
    vhdl: ["VHDL", ["vhdl"]],
    vim: ["vim", ["vim"]],
    "visual-basic": ["Visual Basic", ["visual-basic","vb"]],
    wasm: ["WebAssembly", ["wasm"]],
    wiki: ["Wiki markup", ["wiki"]],
    xeora: ["Xeora", ["xeora"]],
    xojo: ["Xojo (REALbasic)", ["xojo"]],
    xquery: ["XQuery", ["xquery"]],
    yaml: ["YAML", ["yaml","yml"]],
    zig: ["Zig", ["zig"]]
  };

  module.exports = prismLanguages
  