const prismLanguages = {
  XML: "markup",
  SVG: "markup",
  MathML: "markup",
  JavaScript: "javascript",
  TypeScript: "typescript",
  Python: "python",
  Java: "java",
  C: "c",
  "C++": "cpp",
  "C#": "csharp",
  PHP: "php",
  Ruby: "ruby",
  Go: "go",
  Rust: "rust",
  Swift: "swift",
  Kotlin: "kotlin",
  Bash: "bash",
  PowerShell: "powershell",
  SQL: "sql",
  JSON: "json",
  CSS: "css",
  SCSS: "scss",
  Less: "less",
  YAML: "yaml",
  Markdown: "markdown",
  GraphQL: "graphql",
  Docker: "docker",
  Git: "git",
  INI: "ini"
};

export default prismLanguages
